Creation of the "dados-de-usuario" branch and creation of PetService
Miaumarro-Petshop/Miaumarro-API pull request #11
Opened 2022-07-28 00:14 UTC by mairaholi

Tive algumas dificuldades durante a criação dos validators para os dados dos Pets, que deixei comentado no código. Falta
- [ ] Um validador para checar se o usuário selecionado existe (não sei se é realmente necessário, já que o pet só pode ser criado se o usuário estiver logado). - eu comecei a implementação, mas para isso teria que ter uma comunicação com o banco e dados que eu não sei bem como fazer;
- [ ] Um validador para verificar se o PetType e o PetGender selecionados são válidos (não sei se dá para criar um único validador que trataria qualquer enum);
- [ ] Um validador para verificar se o URL da imagem do pet é válido (não tenho ideia de como se faria isso ou se é possível);
- [ ] Um validador para verificar se a data de nascimento colocada não é absurda (por exemplo, data no futuro ou um bicho com mais de 30/50 anos).

Enfim, deixei comentado algumas soluções que pensei. Isso foi o que eu fiz hoje, e estou fazendo o pull request para caso tenham algo muito errado, vocês possam me alertar. Amanhã retomo o trabalho procurando solução para os problemas que faltam.

2022-07-28 03:56 UTC, Kaoticz requested changes
Esse pull request será longo e difícil. Não tenha medo de pedir ajuda caso você trave em algum problema.

2022-07-28 03:56 UTC, Kaoticz commented on MiauAPI/Models/Requests/CreatedPetRequest.cs
> +public sealed record CreatedPetRequest(UserEntity User, string Name, PetType Type, PetGender Gender, string? Breed, string? ImageFileUrl, DateTime DateOfBirth);
Imagens serão salvas localmente no servidor, portanto não tem como o cliente saber de antemão onde o arquivo será guardado. Fiz [uma pesquisa](https://www.appsloveworld.com/image-upload-in-net-core-web-api) e parece que `IFormFile` é o tipo correto pra fazer upload de arquivos, o que inclui imagens.

A imagem então será salva localmente e seu endereço no sistema de arquivos será salvo no banco de dados, para futura referência. Esse endereço nunca será exposto ao usuário.

2022-07-28 03:56 UTC, Kaoticz commented on MiauAPI/Services/PetService.cs
> +            ImageFileUrl = request.ImageFileUrl,
Reiterando o que falei, imagens devem ser salvas localmente, e então sua localização no sistema de arquivos deve ser salva aqui.

2022-07-28 03:56 UTC, Kaoticz commented on MiauAPI/Validators/CreatedPetRequestValidator.cs
> +            //Acho que precisa adicionar um validador para verificar se o url é válido, mas não sei como fazer
Supondo que você use um `IFormFile` para a imagem, dá pra validar checando se `IFormFile.ContentType` é igual a `image/png`.
Vide https://www.iana.org/assignments/media-types/media-types.xhtml#image

2022-07-28 03:56 UTC, Kaoticz commented on MiauAPI/Validators/CreatedPetRequestValidator.cs
> +        //Acho que precisa adicionar um validador para verificar se a data é válida (se não é no futuro ou se o pet tem mais de 30 anos, não sei)
Sim. Você pode criar um método em `Validate` que determina se uma data está dentro de um intervalo especificado.

2022-07-28 03:56 UTC, Kaoticz commented on MiauAPI/Validators/Validate.cs
> +   */
Não acho que isso aqui seja necessário.

2022-07-29 19:46 UTC, mairaholi commented
Acho que o PetService está pronto. Se estiver tudo certo com ele, já começo a trabalhar nos outros Services, como de Endereço e Pedidos.

2022-07-30 18:34 UTC, Kaoticz approved these changes
Bom trabalho. Faltam uns pequenos retoques, mas já vou deixar aprovado porque eles não são  muito importantes.

2022-07-30 18:34 UTC, Kaoticz commented on MiauAPI/Services/PetService.cs
> +//using Encrypt = BCrypt.Net.BCrypt;
Evite commitar código comentado.

2022-07-30 18:34 UTC, Kaoticz commented on MiauAPI/Services/PetService.cs
> +        using (var fileStream = new FileStream(Path.Combine(path, filename), FileMode.Create))
[Estilo]
Você pode usar
```cs
using var fileStream = ...
```
Ao invés de
```cs
using (var fileStream = ...)
{
   ...
}
```

2022-07-30 18:34 UTC, Kaoticz commented on MiauAPI/Services/PetService.cs
> +            ImagePath = "images/" + filename,
Talvez seja uma boa ideia deixar o caminho dos arquivos como `images/id/filename.png` ou `images/cpf/filename.png`, pra evitar problemas caso usuários diferentes tentem fazer upload de imagens com o mesmo nome.

2022-07-30 18:34 UTC, Kaoticz commented on MiauAPI/Validators/CreatedPetRequestValidator.cs
> +        }
Verificamos ontem que não é necessário checar os enums, então você pode remover isso aqui.

2022-07-30 18:34 UTC, Kaoticz commented on MiauAPI/Validators/CreatedPetRequestValidator.cs
> +        //Acho que precisa adicionar um validador para verificar se a data é válida (se não é no futuro ou se o pet tem mais de 30 anos, não sei)
Pode remover o comentário.

2022-08-02 13:27 UTC, mairaholi commented on MiauAPI/Services/PetService.cs
> +        using (var fileStream = new FileStream(Path.Combine(path, filename), FileMode.Create))
Tipo assim? 
![image](https://user-images.githubusercontent.com/73367372/182386045-79e0117e-3f1c-49ad-8979-9bf70859364f.png)

2022-08-02 13:28 UTC, mairaholi commented on MiauAPI/Services/PetService.cs
> +            ImagePath = "images/" + filename,
Assim? 
![image](https://user-images.githubusercontent.com/73367372/182386348-ff16de7a-7fc2-40df-b0fd-9a6cf55b3c2d.png)

2022-08-02 13:34 UTC, mairaholi commented on MiauAPI/Services/PetService.cs
> +            ImagePath = "images/" + filename,
Acabei de verificar, e essa parte realmente estava errado 
![image](https://user-images.githubusercontent.com/73367372/182387610-db1c0c82-c915-4b09-b785-353d4294ca98.png)
Deixei assim, acho que agora está certo, porque aí a imagem vai para o diretório que criamos

2022-08-02 18:17 UTC, Kaoticz commented on MiauAPI/Services/PetService.cs
> +        using (var fileStream = new FileStream(Path.Combine(path, filename), FileMode.Create))
Sim.

2022-08-02 18:17 UTC, Kaoticz commented on MiauAPI/Services/PetService.cs
> +            ImagePath = "images/" + filename,
Blz

2022-08-03 00:20 UTC, merged