Wish list
Miaumarro-Petshop/Miaumarro-API pull request #30
Opened 2022-08-24 01:51 UTC by sekimzero

Criado Wish List, funcionando.

2022-08-24 17:37 UTC, Kaoticz requested changes

2022-08-24 17:37 UTC, Kaoticz commented on MiauAPI/Extensions/IServiceCollectionExt.cs
> +            //.AddScoped<PurchaseService>()
O comentário é intencional?

2022-08-24 17:37 UTC, Kaoticz commented on MiauDatabase/Entities/ProductReviewEntity.cs
> +    public UserEntity User { get; init; } = null!;
Por que mudar de anulável para não-anulável?

2022-08-24 17:37 UTC, Kaoticz commented on MiauDatabase/Entities/WishlistEntity.cs
> +public sealed record WishListEntity : MiauDbEntity
Quando mudar o nome de uma classe/record/struct, você deve também mudar o nome do arquivo.

2022-08-24 17:37 UTC, Kaoticz commented on MiauDatabase/MiauDbContext.cs
> +    public DbSet<WishListEntity> WishLists { get; init; } = null!;
Mudar o nome de um `DbSet<T>` requer a criação de uma migração.

2022-08-24 17:37 UTC, Kaoticz commented on MiauAPI/Models/QueryObjects/ProductReviewObject.cs
> +}
Você pode reescrever esse `record` com [sintaxe posicional](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#positional-syntax-for-property-definition).

2022-08-24 17:37 UTC, Kaoticz commented on MiauAPI/Models/QueryObjects/WishListObject.cs
> +}
Você pode reescrever esse `record` com [sintaxe posicional](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#positional-syntax-for-property-definition).

2022-08-26 19:56 UTC, sekimzero reviewed
Alteracoes feitas em nova commit

2022-08-26 23:04 UTC, Kaoticz commented on MiauDatabase/Entities/ProductReviewEntity.cs
> +    public UserEntity User { get; init; } = null!;
E o que acontece se o usuário for excluído do banco de dados?

2022-08-27 21:04 UTC, Kaoticz commented
Caducado pelo #31

2022-08-27 21:04 UTC, closed without merging